### PR TITLE
Switch license to MIT

### LINKED ISSUE #11: Change license to e.g. MIT?
Since AliasTables depends on PtrArrays, the license of PtrArrays is problematic for downstream packages such as Distributions or StatsBase that want to avoid (or at least minimize) GPL dependencies. See e.g. https://github.com/JuliaStats/Distributions.jl/issues/1864. Based on https://github.com/JuliaStats/Distributions.jl/issues/1864#issuecomment-2137579052, I assume it might be possible to relicense PtrArrays under the MIT license?

### PR DESCRIPTION
**Pull request by LilithHafner**
Closes #11

Approval from @lkdvos [here](https://github.com/LilithHafner/PtrArrays.jl/issues/11#issuecomment-2142563848)

### CODE REVIEW

**Comment by devmotion** [comment]
It seems this might be good to be merged and released? 🙂

**Comment by devmotion** [comment]
Great, thank you! Could you also tag a new release with the license change?

**Comment by LilithHafner** [comment]
That's not necessary. Applying a license to a chunk of code (as I have just done) is the act that legally makes the code available under that license. The code in this repo right now is literally identical to the code released as 1.2.0 so folks may use that version under the terms of the MIT license if they wish.

**Comment by devmotion** [comment]
While a new release might not be required legally, it would still be helpful: Otherwise checks for dependencies with GPL licenses with eg https://github.com/ericphanson/LicenseCheck.jl will continue flagging PtrArrays as problematic.

**Comment by PatrickHaecker** [comment]
Thanks for changing the license.

Indeed having a new release would help us save some work, too. If you only want to do a new release with changed source code, you could add a reference in line 32 pointing to what exactly is buggy in Core.checked_dims.

I recognize that it creates some work on your side, but with multiple users it would still be better than a zero-sum game. And I am pretty sure creating a new release is more fun than having discussions with the legal department before shipping. :-)

**Comment by syarra** [comment]
Thanks for updating the license terms! 

> While a new release might not be required legally, it would still be helpful: Otherwise checks for dependencies with GPL licenses with eg https://github.com/ericphanson/LicenseCheck.jl will continue flagging PtrArrays as problematic.

That would indeed be helpful!

**Pull request merged**
